### ISSUE TITLE
Unexpected token . from scss

### ISSUE THREAD

**Issue by MehdiAghighi** [kuflash/react-router-sitemap#104]
when i try to run the sitemap-generator file, it gives me unexpected token . from one of my scss files.
i trie the solution from #83 and it didn't help me.

`.babelrc`
```javascript
{
  "ignore": ["node_modules/**/*"],
  "presets": ["@babel/preset-env", "@babel/preset-react"]
}
```

`sitemap-generator.js`
```javascript
require("@babel/register")({
  extends: "./.babelrc",
})
const router = require("./src/sitemap-routes.jsx").default
const Sitemap = require("react-router-sitemap").default

function generateSitemap() {
  return new Sitemap(router).build("https://linom.ir").save("./public/sitemap.xml")
}

generateSitemap()
```

`error`
```
/home/mehdi/Projects/ostadmef/src/components/index-intro/index-intro.style.scss:1
.index-intro {
^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Object.newLoader [as .js] (/home/mehdi/Projects/ostadmef/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/mehdi/Projects/ostadmef/src/components/index-intro/index-intro.component.jsx:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
```

i also installed these packages
```json
"@babel/cli": "^7.2.3",
    "@babel/core": "^7.2.2",
    "@babel/preset-env": "^7.3.1",
    "@babel/preset-react": "^7.0.0",
    "@babel/register": "^7.0.0",
```

**Comment by hiradyazdan** [comment]
you're gonna have to tell babel explicitly how to compile the file extension you need to ignore, using an empty function. It is kind of ugly but it works. Something like:

```js
require.extensions['.scss'] = () => {}
```

**Comment by MehdiAghighi** [comment]
@hiradyazdan where should i write this code ?

**Comment by hiradyazdan** [comment]
This is a node expression, so it needs to be evaluated as early as possible in the runtime before hitting your script. You probably best to import it from a separate file with your other globally required node tweaks if you need.
