### ISSUE TITLE
I am getting a weird error on import

### ISSUE THREAD

**Issue by NikolasJody** [kuflash/react-router-sitemap#106]
import loadable from 'loadable-components';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at compileFunction (<anonymous>)
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Module._compile (/Users/nikolasjody/development/Likuid-production/garage/aventador/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Object.newLoader [as .js] (/Users/nikolasjody/development/Likuid-production/garage/aventador/node_modules/pirates/lib/index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)

this is my .babelrc, i didnt set my es2015 modules to false
{
    "ignore": [
		"node_modules/**/*"
	],
	"presets": [
		"@babel/preset-env",
		"@babel/preset-react"
	]
}

this is basically me following the steps in 
https://github.com/kuflash/react-router-sitemap/issues/71

ive been going in circles solving one problem after another, they never stop.

here are the versions of my dev dependencies. 
    "@babel/cli": "^7.2.3",
    "@babel/core": "^7.2.2",
    "@babel/node": "^7.10.3",
    "@babel/plugin-proposal-class-properties": "7.1.0",
    "@babel/plugin-syntax-dynamic-import": "^7.0.0",
    "@babel/plugin-transform-modules-commonjs": "7.1.0",
    "@babel/plugin-transform-react-constant-elements": "7.0.0",
    "@babel/plugin-transform-react-inline-elements": "7.0.0",
    "@babel/preset-env": "^7.3.1",
    "@babel/preset-react": "7.0.0",
    "@babel/register": "7.0.0",

i have also installed the newest node.js

**Comment by acomito** [comment]
@NikolasJody any luck?

I can get it working with generic routes but not my actual routes which have other imports from third party libraries (like antd design)

**Comment by mkhoussid** [comment]
As specified in the [docs](https://www.npmjs.com/package/react-router-sitemap),

> Please note that in this case you need a module 'babel-register' to work with the ES2105 syntax and .jsx format.

So, you need to add the package `babel-register` and require it in your script
