### ISSUE TITLE
sessionStorage, document is not defined...

### ISSUE THREAD

**Issue by RostislavBerezhnoy** [kuflash/react-router-sitemap#61]
Добрый день.
Возникла небольшая проблема, при запуске скрипта:

````
require.extensions['.css'] = function () {
    return null;
};

require.extensions['.jpg'] = function () {
    return null;
};

require('babel-register');
require('babel-polyfill');

const Root = require('./src/index').default;
const Sitemap = require('react-router-sitemap').default;

(
    new Sitemap(Root)

        .build('http://localhost:3000/')
        .save('./public/sitemap.xml')
);
`````
появилось много ошибок, таких как: 
`````
F:\Berezhnoy\Projects\EZteam-frontend\src\reducers\initialState.js:7
    session: !!sessionStorage.token,

ReferenceError: sessionStorage is not defined
    at Object.<anonymous> (F:/Berezhnoy/Projects/EZteam-frontend/src/reducers/initialState.js:3:16)
    at Module._compile (module.js:571:32)
    at loader (F:\Berezhnoy\Projects\EZteam-frontend\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (F:\Berezhnoy\Projects\EZteam-frontend\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (F:/Berezhnoy/Projects/EZteam-frontend/src/reducers/sessionReducer.js:2:1)
`````
`````
F:\Berezhnoy\Projects\EZteam-frontend\src\index.js:196
(0, _reactDom.render)(_react2.default.createElement(Root, null), document.getElementById('root'));
                                                                 ^

ReferenceError: document is not defined
    at Object.<anonymous> (F:/Berezhnoy/Projects/EZteam-frontend/src/index.js:103:18)
    at Module._compile (module.js:571:32)
    at loader (F:\Berezhnoy\Projects\EZteam-frontend\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (F:\Berezhnoy\Projects\EZteam-frontend\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (F:\Berezhnoy\Projects\EZteam-frontend\sitemap-builder.js:12:14)
`````

`````
F:\Berezhnoy\Projects\EZteam-frontend\node_modules\react-router-sitemap\index.es5.js:1
(function (exports, require, module, __filename, __dirname) { module.exports=function(e){function t(n){if(r[n])return r[n].exports;var u=r[n]={exports:{},id:n,loaded:!1};return e[n].call(u.exports,u,u.exports,t),u.loaded=!0,u.exports}var r={};return t.m=e,t.c=r,t.p="",t(0)}([function(e,t,r){"use strict";function n(e){return e&&e.__esModule?e:{default:e}}Object.defineProperty(t,"__esModule",{value:!0});var u=r(1);Object.defineProperty(t,"default",{enumerable:!0,get:function(){return n(u).default}}),Object.defineProperty(t,"sitemapBuilder",{enumerable:!0,get:function(){return u.sitemapBuilder}}),Object.defineProperty(t,"routesParser",{enumerable:!0,get:function(){return u.routesParser}}),Object.defineProperty(t,"pathsFilter",{enumerable:!0,get:function(){return u.pathsFilter}}),Object.defineProperty(t,"paramsApplier",{enumerable:!0,get:function(){return u.paramsApplier}})},function(e,t,r){"use strict";function n(e){return e

Error: Need pass router in module
    at new e (F:\Berezhnoy\Projects\EZteam-frontend\node_modules\react-router-sitemap\index.es5.js:1:2037)
    at Object.<anonymous> (F:\Berezhnoy\Projects\EZteam-frontend\sitemap-builder.js:16:5)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
`````

В devDependencies у меня:
`````
"babel-polyfill": "^6.23.0",
"babel-preset-es2015": "^6.24.1",
"babel-preset-react": "^6.24.1",
"babel-register": "^6.24.1",
`````

Подскажите пожалуйста, как можно решить эту проблему? Может я не правильно что-то подключил в скрипте?

**Comment by kuflash** [comment]
@RostislavBerezhnoy дело в том, что скрипт исполняет node.js, а в его окружении нет таких  глобальных объектов, как `document` и `sessionStorage`. И покажите, пожалуйста, ваш файл, который вы импортируете таким образом: `require('./src/index')`. У меня есть ощущение, что там не то, что требует на вход генератор.

**Comment by RostislavBerezhnoy** [comment]
Вот мой require('./src/index')

`````
import React from 'react';
import { render } from 'react-dom';
import 'babel-polyfill';
import "babel-register";
import './bootstrap.css';
import { Router, Route, browserHistory } from 'react-router';

import 'react-s-alert/dist/s-alert-default.css';
import 'react-s-alert/dist/s-alert-css-effects/slide.css';
import 'react-s-alert/dist/s-alert-css-effects/scale.css';
import 'react-s-alert/dist/s-alert-css-effects/bouncyflip.css';
import 'react-s-alert/dist/s-alert-css-effects/flip.css';
import 'react-s-alert/dist/s-alert-css-effects/genie.css';
import 'react-s-alert/dist/s-alert-css-effects/jelly.css';
import 'react-s-alert/dist/s-alert-css-effects/stackslide.css';

import Home from './containers/HomePage/Home.js';
import TeamsPage from './containers/TeamsPage/TeamsPage.js';
import CompetitionsPage from './containers/CompetitionsPage/CompetitionsPage.js';
import TrainingPage from './containers/TrainingPage/TrainingPage.js';
import NotFound from './containers/NotFound/NotFound.js';
import Layout from './components/Layout/Layout';
import LoginPage from './containers/LoginPage/LoginPage';
import RegisterPage from './containers/RegisterPage/RegisterPage';
import HelpPage from './containers/HelpPage/HelpPage';
import EditingAthleteCard from './containers/EditingAthleteCard/EditingAthleteCard';
import EditingCompetitionCard from './containers/EditingCompetitionCard/EditingCompetitionCard';
import CompetitionEventPage from './containers/CompetitionEventPage/CompetitionEventPage.js';
import AthletePage from './containers/AthletePage/AthletePage.js';
import AthleteMergePage from './containers/AthleteMergePage/AthleteMergePage';
import AddAthlete from './containers/AddAthlete/AddAthlete';
import EmptyLayout from './containers/EmptyLayout/EmptyLayout';
import AthleteBind from './containers/AthleteBind/AthleteBind';
import AddCompetition from './containers/AddCompetition/AddCompetition';
import AddTeam from './containers/AddTeam/AddTeam';
import EditTeamPage from './containers/EditTeamPage/EditTeamPage';

import configureStore from './store/configureStore';
import { Provider } from 'react-redux';

import moment from 'moment';
moment.locale('ru');


const store = configureStore();

const Root = () => {
    return (
        <Provider store={store}>
            <Router history={ browserHistory }>
                <Route component={EmptyLayout}>
                    <Route path="/login" component={LoginPage}/>
                </Route>
                <Route component={Layout}>
                    <Route exact path="/" component={Home} />
                    <Route path="/teams" component={TeamsPage} onEnter={requireAuth}/>
                    <Route path="/teams/athlete(/:id)" component={AthletePage} />
                    <Route path="/teams/athlete(/:id/)edit" component={EditingAthleteCard} onEnter={requireAuth}/>
                    <Route path="/teams/athlete(/merge/:id)" component={AthleteMergePage} onEnter={requireAuth}/>
                    <Route path="/teams/new-athlete/add" component={AddAthlete} onEnter={requireAuth}/>
                    <Route path="/teams/bind-athlete" component={AthleteBind} onEnter={requireAuth}/>
                    <Route path="/teams/new-team/add" component={AddTeam} onEnter={requireAuth}/>
                    <Route path="/teams/edit-team" component={EditTeamPage} onEnter={requireAuth}/>

                    <Route path="/competitions" component={CompetitionsPage} />
                    <Route path="/competitions/:id" component={ CompetitionEventPage } />
                    <Route path="/competitions/:id/edit" component={EditingCompetitionCard} onEnter={requireAuth}/>
                    <Route path="/competitions/new-competition/add" component={AddCompetition} onEnter={requireAuth}/>

                    <Route path="/training" component={TrainingPage}/>
                    <Route path="/help" component={HelpPage}/>
                    <Route path="/register" component={RegisterPage}/>

                    <Route path='*' component={NotFound} />
                </Route>
            </Router>
        </Provider>

    )
};


function requireAuth(nextState, replace) {
    if (!sessionStorage.token) {
        replace({
            pathname: '/login',
            state: nextState.location.pathname
        });

    }
}

render(<Root />, document.getElementById('root'));

`````

**Comment by kuflash** [comment]
@RostislavBerezhnoy вам необходимо отделить конфигурацию маршрутов от самой инициализации приложения. Вот посмотрите, как сделано тут: [RouterConfig](https://github.com/CSSSR/csssr.ru/blob/master/app/routes.jsx), [App](https://github.com/CSSSR/csssr.ru/blob/master/app/app.jsx)

**Comment by RostislavBerezhnoy** [comment]
Спасибо Вам больше, я отделил и все получилось! 
Осталось только конфигами заняться чтобы пофиксить динамические урлы.
