### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by saadaouad** [kuflash/react-router-sitemap#63]
Hi @kuflash,
I run my scripts using `npm run build:sitemap` and i get this error, i don't know why : 
```
➜  repo-ui git:(fix/issue_96) ✗ npm run build:sitemap

> repo-main@0.1.0 build:sitemap /Users/saadaouad/repo-ui
> node src/core/sitemap-builder.js

/Users/saadaouad/repo-ui/src/core/Router.js:4
import React from 'react';
^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at loader (/Users/saadaouad/repo-ui/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/saadaouad/repo-ui/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
```
### sitemap-builder.js
```
require('babel-register');

require.extensions[
  ('.svg', '.png', '.jpeg', '.jpg', 'css', 'scss', '.ico')
] = function() {
  return null;
};

const router = require('./Router').default;
const Sitemap = require('react-router-sitemap').default;

new Sitemap(router).build('http://localhost:9000').save('./sitemap.xml');
```
Command run scripts 
### package.json
```
"build:sitemap": "node src/core/sitemap-builder.js",
```
### FYI : 
the `Retour.js` working well, and i use `react-router-dom`

Any idea about why i get this error ?

**Comment by kuflash** [comment]
@saadaouad can you show me `.babelrc` file?

**Comment by saadaouad** [comment]
Sure!

### .babelrc
```
{
  "presets": [
    [
      "es2015",
      {
        "modules": false
      }
    ],
    "stage-0",
    "react"
  ],
  "plugins": [
    "react-hot-loader/babel",
    "transform-decorators-legacy",
    [
      "react-intl",
      {
        "messagesDir": "./build/messages/"
      }
    ]
  ],
  "env": {
    "development": {
      "plugins": ["transform-react-jsx-source"]
    }
  }
}
```

**Comment by kuflash** [comment]
@saadaouad maybe it's error is due to `{ "modules": false }`? Try remove this object.

**Comment by saadaouad** [comment]
Yep working well @kuflash, thanks a lot
