### ISSUE TITLE
Cannot read property func of undefined

### ISSUE THREAD

**Issue by merlinpatt** [kuflash/react-router-sitemap#77]
I just did a fresh install of this and got the following error

```
W20180902-10:24:25.322(-4)? (STDERR) TypeError: Cannot read property 'func' of undefined
W20180902-10:24:25.322(-4)? (STDERR)     at Object.<anonymous> (/Users/merlin/code/clever-beagle/pup/node_modules/react-router-sitemap/node_modules/react-router/lib/InternalPropTypes.js:9:29)
W20180902-10:24:25.322(-4)? (STDERR)     at Module._compile (module.js:652:30)
W20180902-10:24:25.322(-4)? (STDERR)     at Object.Module._extensions..js (module.js:663:10)
W20180902-10:24:25.322(-4)? (STDERR)     at Module.load (module.js:565:32)
W20180902-10:24:25.323(-4)? (STDERR)     at tryModuleLoad (module.js:505:12)
W20180902-10:24:25.323(-4)? (STDERR)     at Function.Module._load (module.js:497:3)
W20180902-10:24:25.323(-4)? (STDERR)     at Module.require (module.js:596:17)
W20180902-10:24:25.323(-4)? (STDERR)     at require (internal/module.js:11:18)
W20180902-10:24:25.323(-4)? (STDERR)     at Object.<anonymous> (/Users/merlin/code/clever-beagle/pup/node_modules/react-router-sitemap/node_modules/react-router/lib/PropTypes.js:12:26)
W20180902-10:24:25.324(-4)? (STDERR)     at Module._compile (module.js:652:30)
```

**Comment by Cretezy** [comment]
Somehow this package depends on React 15, which included the PropType package, and you are using 16 which removed it.

We ran in the same issue, you can use the `@cretezy/react-router-sitemap` package which solves this, I'll be doing a PR to this repo soon to try to get the fix upstream

**Comment by n3ssi3** [comment]
I just installed the latest version, and now I get the following error.
Am I doing something wrong?
("react": "^16.3.2", "react-router": "^4.2.0")

````
> node scripts/sitemap-builder.js

/myproject/node_modules/react-router-sitemap/index.es5.js:1
(function (exports, require, module, __filename, __dirname) { module.exports=function(e){function t(n){if(r[n])return r[n].exports;var u=r[n]={exports:{},id:n,loaded:!1};return e[n].call(u.exports,u,u.exports,t),u.loaded=!0,u.exports}var r={};return t.m=e,t.c=r,t.p="",t(0)}([function(e,t,r){"use strict";function n(e){return e&&e.__esModule?e:{default:e}}Object.defineProperty(t,"__esModule",{value:!0});var u=r(1);Object.defineProperty(t,"default",{enumerable:!0,get:function(){return n(u).default}}),Object.defineProperty(t,"sitemapBuilder",{enumerable:!0,get:function(){return u.sitemapBuilder}}),Object.defineProperty(t,"routesParser",{enumerable:!0,get:function(){return u.routesParser}}),Object.defineProperty(t,"pathsFilter",{enumerable:!0,get:function(){return u.pathsFilter}}),Object.defineProperty(t,"paramsApplier",{enumerable:!0,get:function(){return u.paramsApplier}})},function(e,t,r){"use strict";function n(e){return e&&e.__es

TypeError: (0 , m.createRoutes) is not a function
    at new e (/myproject/node_modules/react-router-sitemap/index.es5.js:1:2101)
    at Object.<anonymous> (/myproject/scripts/sitemap-builder.js:13:3)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:240:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:564:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! project@0.1.0 build-sitemap: `node scripts/sitemap-builder.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the project@0.1.0 build-sitemap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!    .npm/_logs/2018-09-25T04_40_31_218Z-debug.log

````

**Comment by kuflash** [comment]
@n3ssi3 unfortunately this library does not work with react-router 4
