### ISSUE TITLE
m.createRoutes is not a function

### ISSUE THREAD

**Issue by francisrod01** [kuflash/react-router-sitemap#85]
The version latest: `1.2.0` have this bug on the compilation.

```js
const ignoreStyles = require('ignore-styles');
const register = ignoreStyles.default;

const extensions = ['css', 'scss', 'sass', 'less'];

register(ignoreStyles.DEFAULT_EXTENSIONS, (mod, filename) => {
  if (extensions.find(f => filename.endsWith(f))) {
    return ignoreStyles.noOp();
  }
});

require('@babel/polyfill');
require('@babel/register');

const Sitemap = require('react-router-sitemap').default;
const router = require('./src/routes').default;

const filterConfig = {
  isValid: false,
  rules: [/\/admin/, /\*/],
};

const sitemap = (
  new Sitemap(router)
    .filterPaths(filterConfig)
    .build('https://mywebpage.net')
    .save('./sitemap.xml', '/build/')
);
```

On console:

```bash
$ node sitemap-builder.js 
/home/paneladm/projects/paneladm-dev/website/node_modules/react-router-sitemap/index.es5.js:1
(function (exports, require, module, __filename, __dirname) { module.exports=function(e){function t(n){if(r[n])return r[n].exports;var u=r[n]={exports:{},id:n,loaded:!1};return e[n].call(u.exports,u,u.exports,t),u.loaded=!0,u.exports}var r={};return t.m=e,t.c=r,t.p="",t(0)}([function(e,t,r){"use strict";function n(e){return e&&e.__esModule?e:{default:e}}Object.defineProperty(t,"__esModule",{value:!0});var u=r(1);Object.defineProperty(t,"default",{enumerable:!0,get:function(){return n(u).default}}),Object.defineProperty(t,"sitemapBuilder",{enumerable:!0,get:function(){return u.sitemapBuilder}}),Object.defineProperty(t,"routesParser",{enumerable:!0,get:function(){return u.routesParser}}),Object.defineProperty(t,"pathsFilter",{enumerable:!0,get:function(){return u.pathsFilter}}),Object.defineProperty(t,"paramsApplier",{enumerable:!0,get:function(){return u.paramsApplier}})},function(e,t,r){"use strict";function n(e){r

TypeError: (0 , m.createRoutes) is not a function
    at new e (/home/paneladm/projects/paneladm-dev/website/node_modules/react-router-sitemap/index.es5.js:1:2101)
    at Object.<anonymous> (/home/paneladm/projects/paneladm-dev/website/sitemap-builder.js:25:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

**Comment by The-Code-Monkey** [comment]
You don't seem to be ignoring node modules I think you have to ignore them

**Comment by kuflash** [comment]
@francisrod01 Are you sure, what react-router-sitemap is updated to 1.2.0 in your project? A similar error usually yielded when there was no support ReactRouter V4.

**Comment by francisrod01** [comment]
I'm sorry for that.
I was confused. Npm shows me the latest version usin `npm info`.
Now it's work.

**Comment by francisrod01** [comment]
@kuflash What I could do to solve the `param` problem? Using database to list those urls?

```xml
<url> <loc>https://my-page.net/</loc> </url>
<url> <loc>https://my-page.net/about</loc> </url>
<url> <loc>https://my-page.net/contact</loc> </url>
<url> <loc>https://my-page.net/company/:id</loc> </url>
<url> <loc>https://my-page.net/know-more/business</loc> </url>
<url> <loc>https://my-page.net/city-promotion</loc> </url>
<url> <loc>https://my-page.net/city-promotion/:slug</loc> </url>
<url> <loc>https://my-page.net/city-promotion/:slug/event/:eventSlug</loc> </url>
<url> <loc>https://my-page.net/city-promotion/:slug/ad-sample</loc> </url>
```

**Comment by kuflash** [comment]
@francisrod01 it's another question. Can you create separate issue?

**Comment by francisrod01** [comment]
Yes. There's no possible to generate all links based on the routes #86

**Comment by The-Code-Monkey** [comment]
There is you just have to do a fetch with a dB call that gets the slugs from your dB and format it in the way for params to work I'll show you our setup at work tomorrow when I do it for out latest project

**Comment by francisrod01** [comment]
> There is you just have to do a fetch with a dB call that gets the slugs from your dB and format it in the way for params to work I'll show you our setup at work tomorrow when I do it for out latest project

Yes, I know. Before to implement that I've been creating a table structure separating all the SEO including all slugs related by the topics. That way prevents I created a VIEW or something else in MongoDB further to index millions of links.
