### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by jon-moreira** [kuflash/react-router-sitemap#91]
When i try to run my sitemap-builder.js i get this error:

```
$ node sitemap-builder.js 
sources/node_modules/babel-core/lib/transformation/file/index.js:558
      throw err;
      ^

SyntaxError: sources/src/routing.js: Unexpected token (20:6)
  18 |   render() {
  19 |     return (
> 20 |       <BrowserRouter>
     |       ^
  21 |         <Switch>
  22 |             <Route path="/" exact={true} component={Wrapper(App)} />
  23 |             <Route path="/about-us" component={Wrapper(AboutUs)} />
    at Parser.pp$5.raise (/sources/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/sources/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$3.parseExprAtom (/sources/node_modules/babylon/lib/index.js:3750:12)
    at Parser.pp$3.parseExprSubscripts (/sources/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/sources/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/sources/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/sources/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/sources/node_modules/babylon/lib/index.js:3344:19)
    at Parser.pp$3.parseParenAndDistinguishExpression (/sources/node_modules/babylon/lib/index.js:3828:26)
    at Parser.pp$3.parseExprAtom (/sources/node_modules/babylon/lib/index.js:3709:19)
```

**### sitemap-builder.js**

```
require('babel-register');

const router = require('./src/routing').default;
const Sitemap = require('../').default;

(
    new Sitemap(router)
        .build('http://mywebsiteurl.com')
        .save('./sitemap.xml')
);
```

**### routing.js**

```
import React from "react";
import { BrowserRouter, Switch, Route } from 'react-router-dom'

import App from './App';
import NotFound from './pages/not_found';
import AboutUs from './pages/about_us';
import PortFolioItem from "./pages/portfolio_item/portfolio-item";
import Contact from './pages/contact';

import Wrapper from "./components/Wrapper";


class Routing extends React.Component {
  render() {
    return (
      <BrowserRouter>
        <Switch>
            <Route path="/" exact={true} component={Wrapper(App)} />
            <Route path="/about-us" component={Wrapper(AboutUs)} />
            <Route path="/contact" component={Wrapper(Contact)} />
            <Route path="/portfolio-item/:collection" component={Wrapper(PortFolioItem)} />
            <Route component={NotFound} />
        </Switch>
      </BrowserRouter>
    );
  }
}

export default Routing;
```

**Comment by kuflash** [comment]
@expouic can you create test project with this error?

**Comment by bert27** [comment]
the same
